variables:
  CC4S_PATH: "build/gcc-oblas-ompi/bin/Cc4s"
  CC4S_RUN: "salloc -N1 -n4 mpirun build/gcc-oblas-ompi/bin/Cc4s"
  CONFIG: "gcc-oblas-ompi"
  NP: 4

stages:
  - build
  - test

build:
  stage: build
  only:
    - master
    - develop
  script:
    - salloc -N1 -n1 mpirun make CONFIG=$CONFIG -j$NP -s extern
    - salloc -N1 -n1 mpirun make CONFIG=$CONFIG -j$NP -s
  artifacts:
    paths:
      - "build/*"

test:
  stage: test
  only:
    - master
    - develop
  needs:
    - job: build
      artifacts: true
  script:
    - make CONFIG=$CONFIG CC4S_RUN="$CC4S_RUN" test-run test-check
