variables:
  CONFIG: "gcc-oblas-ompi"
  NP: 4

stages:
  - build
  - test

build:
  stage: build
  only:
    - master
    - develop
  script:
    - salloc -N1 -n$NP mpirun -np 1 make CONFIG=$CONFIG -j$NP -s extern
    - salloc -N1 -n$NP mpirun -np 1 make CONFIG=$CONFIG -j$NP -s
  artifacts:
    paths:
      - "build/*"

test:
  stage: test
  only:
    - master
    - develop
  needs:
    - job: build
      artifacts: true
  script:
    - salloc -N1 -n$NP make CONFIG=$CONFIG test-run
    - salloc -N1 -n$NP make CONFIG=$CONFIG test-check
