# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # gcc{6,7,8} have been removed from nixpkgs since they're not maintained anymore
        compiler: [gcc9, gcc10, gcc11, gcc12, gcc13, gcc14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Fetch dependencies sources
      run: make fetch-dependencies CONFIG=dist

    - name: Fetch test data
      run: make test-data CONFIG=dist

    - name: ${{matrix.compiler}} build extern
      run: ./tools/compile-and-test-nix.sh ${{matrix.compiler}}
      env:
        CI_MAKE_RULE: extern

    - name: ${{matrix.compiler}} build cc4s
      run: ./tools/compile-and-test-nix.sh ${{matrix.compiler}}
      env:
        CI_MAKE_RULE: cc4s

    - name: ${{matrix.compiler}} tests (run)
      run: ./tools/compile-and-test-nix.sh ${{matrix.compiler}}
      env:
        CI_MAKE_RULE: test-run

    - name: ${{matrix.compiler}} tests (check)
      run: ./tools/compile-and-test-nix.sh ${{matrix.compiler}}
      env:
        CI_MAKE_RULE: test-check
